use std::{io::Cursor, path::Path, time::Duration};

use image::{DynamicImage, ImageFormat, Rgb, RgbImage};
use serde_json::{Value, json};
use url::Url;

use super::{
    SogniClient,
    project_wire_server::{Fixture, KEY},
};
use crate::{AssetRole, MediaSource, ProjectRequest};

const PROJECT: &str = "00000000-0000-4000-8000-000000000000";

// Generated by the unmodified @sogni-ai/sogni-client 5.28.0 serializer.
// Keep the whole document: object equality detects unexpected fields as well
// as missing worker-reset nulls, arrays, and guide-conditioning parameters.
const OFFICIAL_WIRE: &str = include_str!("fixtures/guide-request.json");

#[tokio::test]
async fn full_guide_create_matches_official_wire_and_upload_contract() {
    let image = RgbImage::from_fn(1024, 1024, |x, y| {
        Rgb([
            u8::try_from(x / 4).unwrap(),
            u8::try_from(y / 4).unwrap(),
            if (x / 128 + y / 128) % 2 == 0 {
                40
            } else {
                200
            },
        ])
    });
    let mut png = Cursor::new(Vec::new());
    DynamicImage::ImageRgb8(image)
        .write_to(&mut png, ImageFormat::Png)
        .unwrap();
    verify_create(png.into_inner(), None, false, false).await;
}

#[tokio::test]
async fn reserved_guide_upload_is_associated_before_submission_without_duplicate_upload() {
    let mut png = Cursor::new(Vec::new());
    DynamicImage::ImageRgb8(RgbImage::from_pixel(1024, 1024, Rgb([64, 128, 192])))
        .write_to(&mut png, ImageFormat::Png)
        .unwrap();
    verify_create(png.into_inner(), None, true, false).await;
}

#[tokio::test]
async fn full_z_image_guide_create_matches_official_comfy_wire_and_upload_contract() {
    let mut png = Cursor::new(Vec::new());
    DynamicImage::ImageRgb8(RgbImage::from_pixel(1024, 1024, Rgb([64, 128, 192])))
        .write_to(&mut png, ImageFormat::Png)
        .unwrap();
    verify_create(png.into_inner(), None, true, true).await;
}

#[tokio::test]
#[ignore = "offline retained synthetic PNG comparison requires explicit local fixture paths"]
async fn retained_png_full_create_matches_official_wire_and_upload_contract() {
    let input = std::env::var("SOGNI_WIRE_FIXTURE_PNG").unwrap();
    let output = std::env::var("SOGNI_WIRE_CAPTURE_DIR").unwrap();
    let png = tokio::fs::read(input).await.unwrap();
    assert!(png.starts_with(b"\x89PNG\r\n\x1a\n"));
    let z_image = std::env::var("SOGNI_WIRE_FIXTURE_MODEL").as_deref() == Ok("z_image_turbo_bf16");
    verify_create(png, Some(Path::new(&output)), z_image, z_image).await;
}

async fn verify_create(png: Vec<u8>, output: Option<&Path>, reserve_guide: bool, z_image: bool) {
    let mut fixture = Fixture::start().await;
    let endpoint = format!("http://{}/", fixture.address);
    let client = SogniClient::builder()
        .api_key(KEY)
        .rest_endpoint(Url::parse(&endpoint).unwrap())
        .socket_endpoint(Url::parse(&format!("ws://{}/", fixture.address)).unwrap())
        .request_timeout(Duration::from_secs(3))
        .connect_timeout(Duration::from_secs(3))
        .build()
        .await
        .unwrap();
    let model = if z_image {
        "z_image_turbo_bf16"
    } else {
        "flux1-schnell-fp8"
    };
    let request = ProjectRequest::image(model, "Synthetic parity fixture")
        .steps(if z_image { 8 } else { 5 })
        .guidance(1.0)
        .dimensions(1024, 1024)
        .param("numberOfPreviews", 0)
        .param("seed", 123)
        .param("sampler", if z_image { "res_multistep" } else { "euler" })
        .param("scheduler", "simple")
        .param("startingImageStrength", 0.75);
    let guide = "00000000-0000-4000-8000-000000000001";
    let request = if reserve_guide {
        client
            .projects
            .upload_guide_image(PROJECT, guide, &MediaSource::bytes(png.clone()))
            .await
            .unwrap();
        assert!(
            fixture.wire.try_recv().is_err(),
            "upload alone cannot submit a project"
        );
        request.param("startingImage", true)
    } else {
        request.asset(AssetRole::StartingImage, MediaSource::bytes(png.clone()))
    };
    tokio::time::timeout(
        Duration::from_secs(8),
        client.projects.create_with_id(PROJECT, request),
    )
    .await
    .unwrap()
    .unwrap();
    let actual = tokio::time::timeout(Duration::from_secs(3), fixture.wire.recv())
        .await
        .unwrap()
        .unwrap();
    client.close().await.unwrap();
    let wire = if z_image {
        include_str!("fixtures/z-image-guide-request.json")
    } else {
        OFFICIAL_WIRE
    };
    let mut expected: Value = serde_json::from_str(wire).unwrap();
    // JSON does not distinguish integer/floating representations of dimensions.
    expected["keyFrames"][0]["width"] = json!(1024.0);
    expected["keyFrames"][0]["height"] = json!(1024.0);
    expected["keyFrames"][0]["guidanceScale"] = json!(1.0);
    pretty_assertions::assert_eq!(actual, expected);
    let http = fixture.http.lock().clone();
    let registrations = http
        .iter()
        .filter(|r| r.path == "/v1/image/uploadUrl")
        .collect::<Vec<_>>();
    assert_eq!(
        registrations.len(),
        1,
        "guide only; no accidental masks or references"
    );
    let registration = registrations[0];
    assert_eq!(registration.method, "GET");
    assert_eq!(registration.query.len(), 4);
    assert_eq!(registration.query["jobId"], PROJECT);
    assert_eq!(registration.query["type"], "startingImage");
    assert_eq!(registration.query["contentType"], "image/png");
    if reserve_guide {
        assert_eq!(registration.query["imageId"], guide);
    }
    let image_id = uuid::Uuid::parse_str(&registration.query["imageId"]).unwrap();
    assert_eq!(
        registration.query["imageId"],
        image_id.to_string().to_uppercase()
    );
    let uploads = http
        .iter()
        .filter(|r| r.path == "/fixture-upload")
        .collect::<Vec<_>>();
    assert_eq!(uploads.len(), 1);
    assert_eq!(uploads[0].headers["content-type"], "image/png");
    assert!(!uploads[0].headers.contains_key("content-disposition"));
    assert_eq!(
        uploads[0].body, png,
        "registered PNG is uploaded byte-for-byte"
    );
    if let Some(output) = output {
        let name = if z_image {
            "full-create-z-rust"
        } else {
            "full-create-rust"
        };
        tokio::fs::create_dir_all(output).await.unwrap();
        tokio::fs::write(
            output.join(format!("{name}.json")),
            serde_json::to_vec_pretty(&actual).unwrap(),
        )
        .await
        .unwrap();
        tokio::fs::write(output.join(format!("{name}-upload.png")), &uploads[0].body)
            .await
            .unwrap();
        tokio::fs::write(
            output.join(format!("{name}-resource.json")),
            serde_json::to_vec_pretty(&registration.query).unwrap(),
        )
        .await
        .unwrap();
    }
}
