use anyhow::Result;

use super::ImageModelSpec;

const QUALITY_NEGATIVE: &str = "malformation, bad anatomy, bad hands, missing fingers, cropped, low quality, bad quality, jpeg artifacts, watermark";

pub const TEXT_MODELS: &[ImageModelSpec] = &[
    model(
        "z-turbo",
        "z_image_turbo_bf16",
        "Z-Image Turbo",
        1024,
        2048,
        4,
        10,
        8,
        0.6,
        1.6,
        1.0,
        "res_multistep",
        None,
        true,
    ),
    model(
        "z-image",
        "z_image_bf16",
        "Z-Image",
        1024,
        2048,
        20,
        50,
        25,
        1.0,
        7.0,
        4.0,
        "res_multistep",
        None,
        true,
    ),
    model(
        "krea-2-turbo",
        "krea2_turbo_fp8_scaled",
        "Krea 2 Turbo",
        1024,
        2560,
        4,
        12,
        8,
        0.6,
        1.6,
        1.0,
        "euler",
        None,
        true,
    ),
    model(
        "chroma-v46-flash",
        "chroma-v.46-flash_fp8",
        "Chroma v.46 Flash",
        1024,
        2048,
        10,
        20,
        10,
        1.0,
        2.5,
        1.0,
        "euler",
        Some(QUALITY_NEGATIVE),
        true,
    ),
    model(
        "chroma-v48-detail-svd",
        "chroma-v48-detail-svd_fp8",
        "Chroma v48 Detail SVD",
        1024,
        2048,
        20,
        40,
        25,
        3.0,
        8.0,
        5.0,
        "euler",
        Some(QUALITY_NEGATIVE),
        true,
    ),
    model(
        "chroma-hd",
        "chroma1-hd_fp8_scaled",
        "Chroma1-HD",
        1024,
        2048,
        20,
        50,
        26,
        1.0,
        8.0,
        3.8,
        "euler",
        Some(QUALITY_NEGATIVE),
        true,
    ),
    model(
        "flux1-schnell",
        "flux1-schnell-fp8",
        "Flux.1 Schnell",
        1024,
        1536,
        1,
        5,
        4,
        0.1,
        1.0,
        1.0,
        "Euler",
        None,
        false,
    ),
    model(
        "qwen-2512-lightning",
        "qwen_image_2512_fp8_lightning",
        "Qwen Image 2512 Lightning",
        1024,
        2048,
        4,
        8,
        4,
        0.6,
        1.6,
        1.0,
        "euler",
        None,
        true,
    ),
    model(
        "qwen-2512",
        "qwen_image_2512_fp8",
        "Qwen Image 2512",
        1024,
        2048,
        20,
        50,
        25,
        3.0,
        6.0,
        4.0,
        "euler",
        None,
        true,
    ),
    model(
        "dark-beast-z-image-turbo",
        "dark_beast_z_image_turbo_v9_bf16",
        "Dark Beast Z-Image Turbo v9",
        1024,
        2048,
        4,
        12,
        8,
        1.0,
        1.0,
        1.0,
        "res_multistep",
        None,
        true,
    ),
    model(
        "dark-beast-krea-2",
        "dark_beast_krea2_fp8",
        "Dark Beast KREA 2",
        1024,
        2048,
        8,
        20,
        16,
        1.0,
        1.0,
        1.0,
        "euler",
        None,
        true,
    ),
    model(
        "one-obsession-v22",
        "one_obsession_v22_fp16",
        "One Obsession v22",
        1024,
        1920,
        20,
        35,
        28,
        3.0,
        10.0,
        6.0,
        "euler",
        None,
        true,
    ),
];

#[allow(clippy::too_many_arguments)]
const fn model(
    key: &'static str,
    id: &'static str,
    name: &'static str,
    size: u32,
    maximum: u32,
    min_steps: u32,
    max_steps: u32,
    default_steps: u32,
    min_guidance: f64,
    max_guidance: f64,
    default_guidance: f64,
    sampler: &'static str,
    negative_prompt: Option<&'static str>,
    supports_starting_image: bool,
) -> ImageModelSpec {
    ImageModelSpec {
        key,
        id,
        name,
        width: size,
        height: size,
        max_width: maximum,
        max_height: maximum,
        min_steps,
        max_steps,
        default_steps,
        min_guidance,
        max_guidance,
        default_guidance,
        sampler,
        scheduler: "simple",
        negative_prompt,
        supports_starting_image,
        max_context_images: 0,
    }
}

pub fn text_model(key: &str) -> Result<ImageModelSpec> {
    TEXT_MODELS
        .iter()
        .copied()
        .find(|model| model.key == key)
        .ok_or_else(|| anyhow::anyhow!("unknown image model key {key}"))
}
